version: '3.7'

volumes:
    db_data:
        driver: local

services:
    awesome.scot:
        build:
            context: ./build
            dockerfile: ./httpd/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - app

    php:
        build:
            context: ./build
            dockerfile: ./php/Dockerfile
        ports:
            - 9000
            - 9001
        volumes_from:
            - app
        environment:
            APPLICATION_ENV: '${APPLICATION_ENV}'
        user: php:staff

    node:
        build: ./build/node
        volumes_from:
            - app
        ports:
            - 8080:8080
            - 3000:3000

    app:
        image: httpd:2.4.38
        volumes:
            - ./code:/var/www/html
        command: "echo true"

    mariadb:
        image: mariadb:10.7.1
        volumes:
            - ./build/data:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '[123456]'
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: '[123456]'
            MYSQL_DATABASE: laravel  # Agregamos esta línea
        ports:
            - 3306:3306

    mail:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
